
projects_index:
    path:     /projects/
    defaults: { _controller: "TimesheetBundle:Projects:index" }
    methods:  GET

clients_index:
    path:     /clients/
    defaults: { _controller: "TimesheetBundle:Clients:index" }
    methods:  GET

clients_new:
    path:     /clients/new
    defaults: {_controller: "TimesheetBundle:Clients:new"}
    methods:  [GET, POST]

clients_show:
    path:     /clients/{id}/show
    defaults: { _controller: "TimesheetBundle:Clients:show" }
    methods:  GET


leaves:
    path:     /leaves/
    defaults: { _controller: "TimesheetBundle:Leaves:myLeaves" }
    methods:  [GET, POST]

leaves_new:
    path:     /leaves/new
    defaults: {_controller: "TimesheetBundle:Leaves:new"}
    methods:  [GET, POST]

projects_show:
    path:     /projects/{id}/show
    defaults: { _controller: "TimesheetBundle:Projects:show" }
    methods:  GET

projects_new:
    path:     /projects/new
    defaults: { _controller: "TimesheetBundle:Projects:new" }
    methods:  [GET, POST]

projects_edit:
    path:     /projects/{id}/edit
    defaults: { _controller: "TimesheetBundle:Projects:edit" }
    methods:  [GET, POST]

projects_delete:
    path:     /projects/{id}/delete
    defaults: { _controller: "TimesheetBundle:Projects:delete" }
    methods:  DELETE

dayreport_index:
    path:     /dayreport/
    defaults: { _controller: "TimesheetBundle:DayReport:index" }
    methods:  GET

dayreport_show:
    path:     /dayreport/{id}/show
    defaults: { _controller: "TimesheetBundle:DayReport:show" }
    methods:  GET

dayreport_employee:
    path:     /employee/{userid}
    defaults: { _controller: "TimesheetBundle:DayReport:employee" }
    methods:  GET

leaves_employee:
    path:     /employee/leaves/{userid}
    defaults: { _controller: "TimesheetBundle:Leaves:employee" }
    methods:  GET

dayreport_mass_action:
    path:     /employee/massaction
    defaults: { _controller: "TimesheetBundle:DayReport:mass" }
    methods:  [GET, POST]


dayreport_employee_show:
    path:     /employee/{id}/show
    defaults: { _controller: "TimesheetBundle:DayReport:employeeShow" }
    methods:  GET

dayreport_mysheet:
    path:     /mysheet/
    defaults: { _controller: "TimesheetBundle:DayReport:mysheet" }
    methods:  GET

dayreport_new:
    path:     /dayreport/new
    defaults: { _controller: "TimesheetBundle:DayReport:new" }
    methods:  [GET, POST]

dayreport_new_date:
    path:     /dayreport/new/{date}/
    defaults: { _controller: "TimesheetBundle:DayReport:new" }
    methods:  [GET, POST]

dayreport_edit:
    path:     /dayreport/{id}/edit
    defaults: { _controller: "TimesheetBundle:DayReport:edit" }
    methods:  [GET, POST]

dayreport_delete:
    path:     /dayreport/{id}/delete
    defaults: { _controller: "TimesheetBundle:DayReport:delete" }
    methods:  DELETE



