TimesheetBundle\Entity\Clients:
    type: entity
    table: null
    repositoryClass: TimesheetBundle\Repository\ClientsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
