<?php

namespace TimesheetBundle\Repository;

/**
 * AdminConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
