<?php

namespace TimesheetBundle\Repository;

/**
 * DayReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayReportRepository extends \Doctrine\ORM\EntityRepository
{
}
