<?php

namespace TimesheetBundle\Repository;

/**
 * LeavesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeavesRepository extends \Doctrine\ORM\EntityRepository
{
}
