<?php

namespace TimesheetBundle\Repository;

/**
 * ProjectReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectReportRepository extends \Doctrine\ORM\EntityRepository
{
}
